package com.rafaykalim.context.libraries

public class SharedInfo {
    var GOOGLE_SEARCH = 1
    var TRANSLATION = 2
    var DIRECTIONS = 3
    var SPORTS = 4
    var ERROR = 5
    var delimiterList = arrayOf("<", ">", "@", "#", "%", "^", "&", "*", ";", "/")
    var resultInnerDelim = "<>"
    var resultOutterDelim = ";"
    var modes = arrayOf(
        "driving",
        "walking",
        "bicycling",
        "transit"
    )

    var LANGUAGES = arrayOf(
        "not sure",
        "afrikaans",
        "albanian",
        "amharic",
        "arabic",
        "armenian",
        "azerbaijani",
        "basque",
        "belarusian",
        "bengali",
        "bosnian",
        "bulgarian",
        "catalan",
        "cebuano",
        "chichewa",
        "chinese (simplified)",
        "chinese (traditional)",
        "corsican",
        "croatian",
        "czech",
        "danish",
        "dutch",
        "english",
        "esperanto",
        "estonian",
        "filipino",
        "finnish",
        "french",
        "frisian",
        "galician",
        "georgian",
        "german",
        "greek",
        "gujarati",
        "haitian creole",
        "hausa",
        "hawaiian",
        "hebrew",
        "hindi",
        "hmong",
        "hungarian",
        "icelandic",
        "igbo",
        "indonesian",
        "irish",
        "italian",
        "japanese",
        "javanese",
        "kannada",
        "kazakh",
        "khmer",
        "korean",
        "kurdish (kurmanji)",
        "kyrgyz",
        "lao",
        "latin",
        "latvian",
        "lithuanian",
        "luxembourgish",
        "macedonian",
        "malagasy",
        "malay",
        "malayalam",
        "maltese",
        "maori",
        "marathi",
        "mongolian",
        "myanmar (burmese)",
        "nepali",
        "norwegian",
        "pashto",
        "persian",
        "polish",
        "portuguese",
        "punjabi",
        "romanian",
        "russian",
        "samoan",
        "scots gaelic",
        "serbian",
        "sesotho",
        "shona",
        "sindhi",
        "sinhala",
        "slovak",
        "slovenian",
        "somali",
        "spanish",
        "sundanese",
        "swahili",
        "swedish",
        "tajik",
        "tamil",
        "telugu",
        "thai",
        "turkish",
        "ukrainian",
        "urdu",
        "uzbek",
        "vietnamese",
        "welsh",
        "xhosa",
        "yiddish",
        "yoruba",
        "zulu",
        "filipino",
        "hebrew"
    )

    var SPORTS_LIST = arrayOf(
        "baseball",
        "basketball",
        "cricket",
        "football",
        "handball",
        "hockey",
        "rugby-league",
        "rugby-union",
        "soccer",
        "tennis",
        "volleyball"
    )


}